### ISSUE TITLE
Make networkID and destination selectable options to config or not

### ISSUE THREAD

**Issue by stokes776** [ncd-io/ncd-red-wireless-2#4]
There are times I would like to OTF config sensors, but not adjust their networks or destinations.
I have inadverently moved sensors back to 7FFF that were supposed to be on different networks because these two options cannot be turned off, and seemt o go out with every OTF config.

Could these two be made selectable so they could be turned on/off as desired?

![image](https://user-images.githubusercontent.com/50416033/201728289-76a1868a-9486-449c-ae00-f3e70c7d8f05.png)

**Comment by telliottosceola** [comment]
@bhaskar-anil429 @io-Jacob 

Bhaskar, is it required in the sensor firmware to set the Destination and Network ID when configuring settings via OTA?  If not, Jacob, can you make the changes to Node-Red to not send the Destination and Network ID configuration commands(add check box to sensor config UI so these two settings can be disabled)?

**Comment by bhaskar-anil429** [comment]
No we don't need to set these. .yes we should make these user selectable

**Comment by io-Jacob** [comment]
We are finalizing some tests for the 515 sensor OTF, but I have the code to implement this implemented so it should be available later this week.
![Screen Shot 2022-11-14 at 5 10 31 PM](https://user-images.githubusercontent.com/29467331/201791203-187a78f5-01c5-4eb7-bd3b-a8dac9b7e8d5.png)

**Comment by stokes776** [comment]
This is now an option in the newer builds. Closing.
